/** Auto-generated by sync_posts.py - Do not edit manually */
window.BlogPostsData = {
  "schemaVersion": 2,
  "documents": {
    "group-theory-basics": {
      "id": "post-col-group-theory-group-theory-basics",
      "slug": "group-theory-basics",
      "title": "02 群论基础概念测试文档",
      "type": "normal",
      "sourcePath": "posts/02-群论测试.md",
      "relPath": "02-群论测试.md",
      "date": "2026-10-09",
      "category": "general",
      "tags": [
        "test",
        "algebra"
      ],
      "column": "group-theory",
      "columnName": "抽象代数与群论导引",
      "columnDesc": "",
      "order": 2,
      "readTime": "1 min read",
      "words": 207,
      "pinned": false,
      "isTest": true,
      "excerpt": "这是一篇包含 test 标签的专栏测试文档，用于验证专栏路由与测试文档过滤开关。",
      "tocLevels": null,
      "bodyUrl": "data/documents/group-theory-basics.76c36ec8d195693b.json"
    },
    "hello-world": {
      "id": "post-hello-world",
      "slug": "hello-world",
      "title": "Hello World: Welcome to Your Aurora Blog",
      "type": "normal",
      "sourcePath": "posts/hello-world.md",
      "relPath": "hello-world.md",
      "date": "2026-10-09",
      "category": "general",
      "tags": [
        "Engineering",
        "Getting Started",
        "Markdown"
      ],
      "column": "",
      "columnName": "",
      "columnDesc": "",
      "order": 999,
      "readTime": "1 min read",
      "words": 188,
      "pinned": true,
      "isTest": false,
      "excerpt": "Welcome to your new personal blog, designed with Linear and Vercel-inspired dark minimalism.   Getting Started  Writing a new article is as...",
      "tocLevels": null,
      "bodyUrl": "data/documents/hello-world.0aa2edc4b8daf4a9.json"
    },
    "quantum-simulator": {
      "id": "post-quantum-simulator",
      "slug": "quantum-simulator",
      "title": "量子态矢量模拟引擎设计",
      "type": "normal",
      "sourcePath": "posts/quantum-simulator.md",
      "relPath": "quantum-simulator.md",
      "date": "2026-10-09",
      "category": "physics",
      "tags": [
        "quantum",
        "systems",
        "test"
      ],
      "column": "",
      "columnName": "",
      "columnDesc": "",
      "order": 999,
      "readTime": "1 min read",
      "words": 157,
      "pinned": false,
      "isTest": true,
      "excerpt": "基于高维复希尔伯特空间演化的轻量级量子计算仿真核心架构，附带演讲幻灯片展示。",
      "tocLevels": null,
      "bodyUrl": "data/documents/quantum-simulator.4c1db1ae3ad83752.json"
    },
    "roadmap": {
      "id": "post-roadmap",
      "slug": "roadmap",
      "title": "个人发展路线图与白皮书",
      "type": "post",
      "sourcePath": "posts/roadmap.md",
      "relPath": "roadmap.md",
      "date": "2026-10-10",
      "category": "general",
      "tags": [
        "general"
      ],
      "column": "",
      "columnName": "",
      "columnDesc": "",
      "order": 999,
      "readTime": "1 min read",
      "words": 168,
      "pinned": false,
      "isTest": false,
      "excerpt": "关于个人知识库使用约定、开源许可声明与项目发展演进路线图。",
      "tocLevels": [
        2,
        3
      ],
      "bodyUrl": "data/documents/roadmap.034b878b519e9de0.json"
    },
    "group-theory-intro": {
      "id": "post-col-group-theory-group-theory-intro",
      "slug": "group-theory-intro",
      "title": "01 简介：代数结构与映射",
      "type": "normal",
      "sourcePath": "posts/群论/01-简介.md",
      "relPath": "群论/01-简介.md",
      "date": "2026-10-09",
      "category": "群论",
      "tags": [
        "algebra",
        "math"
      ],
      "column": "group-theory",
      "columnName": "抽象代数与群论导引",
      "columnDesc": "从代数结构出发，系统梳理群、环、域的公理化体系与典型同态构造。",
      "order": 1,
      "readTime": "1 min read",
      "words": 135,
      "pinned": false,
      "isTest": false,
      "excerpt": "抽象代数研究代数结构及其公理化体系，从对称性到群环域。",
      "tocLevels": null,
      "bodyUrl": "data/documents/group-theory-intro.cca052151aaf2dfa.json"
    },
    "about": {
      "slug": "about",
      "title": "About",
      "type": "post",
      "sourcePath": "about.md",
      "tocLevels": null,
      "bodyUrl": "data/documents/about.b7e6ec7e7cf72d05.json"
    }
  },
  "aliases": {
    "about": "about",
    "about.md": "about",
    "roadmap": "roadmap",
    "roadmap.md": "roadmap",
    "group-theory-basics": "group-theory-basics",
    "post-col-group-theory-group-theory-basics": "group-theory-basics",
    "posts/02-群论测试.md": "group-theory-basics",
    "02-群论测试.md": "group-theory-basics",
    "hello-world": "hello-world",
    "post-hello-world": "hello-world",
    "posts/hello-world.md": "hello-world",
    "hello-world.md": "hello-world",
    "quantum-simulator": "quantum-simulator",
    "post-quantum-simulator": "quantum-simulator",
    "posts/quantum-simulator.md": "quantum-simulator",
    "quantum-simulator.md": "quantum-simulator",
    "post-roadmap": "roadmap",
    "posts/roadmap.md": "roadmap",
    "group-theory-intro": "group-theory-intro",
    "post-col-group-theory-group-theory-intro": "group-theory-intro",
    "posts/群论/01-简介.md": "group-theory-intro",
    "群论/01-简介.md": "group-theory-intro"
  },
  "posts": [
    "group-theory-basics",
    "hello-world",
    "quantum-simulator",
    "roadmap",
    "group-theory-intro"
  ],
  "columns": [
    {
      "id": "group-theory",
      "name": "抽象代数与群论导引",
      "desc": "从代数结构出发，系统梳理群、环、域的公理化体系与典型同态构造。",
      "icon": "layers",
      "postsCount": 2,
      "totalWords": 342,
      "postIds": [
        "group-theory-intro",
        "group-theory-basics"
      ]
    }
  ],
  "about": "about",
  "searchUrl": "data/search.fdafb06bf0a45f19.json"
};
