/** Auto-generated by sync_posts.py - Do not edit manually */
window.BlogPostsData = {
  "generatedAt": "2026-10-09 16:19:16",
  "posts": [
    {
      "id": "post-hello-world",
      "slug": "hello-world",
      "title": "Hello World: Welcome to Your Aurora Blog",
      "category": "general",
      "column": "",
      "columnName": "",
      "order": 999,
      "relPath": "hello-world.md",
      "date": "2026-10-09",
      "readTime": "4 min read",
      "words": 1278,
      "views": 1,
      "likes": 0,
      "pinned": true,
      "excerpt": "Welcome to your new personal blog, designed with Linear and Vercel-inspired dark minimalism.   Getting Started  Writing a new article is as...",
      "tags": [
        "Engineering",
        "Getting Started",
        "Markdown"
      ],
      "content": "Welcome to your new personal blog, designed with Linear and Vercel-inspired dark minimalism.\n\n## Getting Started\n\nWriting a new article is as simple as placing a Markdown file in the `posts/` directory.\n\n### Folder Structure\n\n- **Regular Articles**: Save any `.md` file directly in `posts/` or under category folders like `posts/tech/my-article.md`.\n- **Series / Columns**: Create a subdirectory inside `posts/columns/`, for example `posts/columns/system-design/01-introduction.md`.\n\n## Features Showcase\n\nHere is a quick demonstration of built-in capabilities:\n\n### 1. Mathematical Formulas (KaTeX)\n\nInline formulas like $$E = mc^2$$ or $$\\left| \\psi \\right\\rangle = \\alpha \\left| 0 \\right\\rangle + \\beta \\left| 1 \\right\\rangle$$, and block equations:\n\n$$\n\\mathcal{L} = \\mathbb{E}_{x \\sim p_{\\text{data}}} \\left[ \\log D(x) \\right] + \\mathbb{E}_{z \\sim p_z} \\left[ \\log (1 - D(G(z))) \\right]\n$$\n\n### 2. Code Highlighting & One-Click Copy\n\n```python\ndef fibonacci(n: int) -> int:\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n\nprint([fibonacci(i) for i in range(10)])\n```\n\n### 3. Callout Boxes\n\n::: tip Quick Publishing\nRun `./deploy.sh` to compile Markdown articles and push changes to GitHub Pages automatically.\n:::\n\nEnjoy crafting your writings!"
    }
  ],
  "columns": []
};
window.BlogSampleData = window.BlogPostsData; // Backwards compatibility
