/** Auto-generated by sync_posts.py - Do not edit manually */
window.BlogPostsData = {
  "generatedAt": "2026-10-09 16:27:18",
  "posts": [
    {
      "id": "post-hello-world",
      "slug": "hello-world",
      "title": "Hello World: Welcome to Your Aurora Blog",
      "category": "general",
      "column": "",
      "columnName": "",
      "order": 999,
      "relPath": "hello-world.md",
      "date": "2026-10-09",
      "readTime": "4 min read",
      "words": 1278,
      "views": 1,
      "likes": 0,
      "pinned": true,
      "excerpt": "Welcome to your new personal blog, designed with Linear and Vercel-inspired dark minimalism.   Getting Started  Writing a new article is as...",
      "tags": [
        "Engineering",
        "Getting Started",
        "Markdown"
      ],
      "content": "Welcome to your new personal blog, designed with Linear and Vercel-inspired dark minimalism.\n\n## Getting Started\n\nWriting a new article is as simple as placing a Markdown file in the `posts/` directory.\n\n### Folder Structure\n\n- **Regular Articles**: Save any `.md` file directly in `posts/` or under category folders like `posts/tech/my-article.md`.\n- **Series / Columns**: Create a subdirectory inside `posts/columns/`, for example `posts/columns/system-design/01-introduction.md`.\n\n## Features Showcase\n\nHere is a quick demonstration of built-in capabilities:\n\n### 1. Mathematical Formulas (KaTeX)\n\nInline formulas like $$E = mc^2$$ or $$\\left| \\psi \\right\\rangle = \\alpha \\left| 0 \\right\\rangle + \\beta \\left| 1 \\right\\rangle$$, and block equations:\n\n$$\n\\mathcal{L} = \\mathbb{E}_{x \\sim p_{\\text{data}}} \\left[ \\log D(x) \\right] + \\mathbb{E}_{z \\sim p_z} \\left[ \\log (1 - D(G(z))) \\right]\n$$\n\n### 2. Code Highlighting & One-Click Copy\n\n```python\ndef fibonacci(n: int) -> int:\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n\nprint([fibonacci(i) for i in range(10)])\n```\n\n### 3. Callout Boxes\n\n::: tip Quick Publishing\nRun `./deploy.sh` to compile Markdown articles and push changes to GitHub Pages automatically.\n:::\n\nEnjoy crafting your writings!"
    }
  ],
  "columns": [],
  "about": "# About Me\n\n> Turning complexity into clean order through rigorous logic, mathematics, and craft.\n\n热爱理论物理与计算机科学的交叉前沿。致力于从高维希尔伯特空间、哈密顿量演化与微观统计力学的物理视角，理解并构建现代大规模计算架构与复杂分布式系统。坚持极简主义与深度心流开发，崇尚用严谨的数学推导与干净的代码建立秩序。\n\n---\n\n## 个人履历与时间线 (Timeline & Milestones)\n\n你可以随时在此编辑自己在不同时间段的经历、项目沉淀与研究方向：\n\n### 2024 – 至今 · 架构设计与前沿计算探索\n- **分布式系统设计**：深耕高吞吐、低延迟分布式共识算法（Raft / Paxos）与跨地域容灾架构。\n- **计算模型研究**：探索量子线路变分模拟、张量网络计算与自注意力机制的物理同构。\n- **极简主义实践**：坚持深度心流开发，追求极致的代码可读性与无冗余工程。\n\n### 2022 – 2024 · 核心系统研发与基础设施优化\n- 主导云原生后端基础设施重构，优化微服务拓扑与多级缓存一致性。\n- 搭建自动化 CI/CD 流水线与端到端高可用监控体系，保障大规模服务稳定性。\n\n### 2020 – 2022 · 现代 Web 架构与工程化探索\n- 深入探索现代前端响应式渲染引擎演进（Virtual DOM Diff、Signals 与 Server Components）。\n- 活跃于开源社区，贡献并维护开发者工具链与数据可视化库。\n\n---\n\n## 核心关注领域 (Focus Areas)\n\n- **分布式系统与高可用架构**：分布式共识协议、一致性存储模型与高并发中间件。\n- **数学与理论物理同构**：复线性代数、高维希尔伯特空间、信息熵与统计热力学。\n- **现代化工程美学**：精细化 Design Tokens、极简暗色交互与极致留白秩序。\n\n---\n\n## 精选项目与工作 (Selected Projects)\n\n- **Aurora Notes**：冷静、克制、严谨的深色科技风个人博客系统。\n- **Distributed Engine**：基于 Go 与 Raft 协议构建的高性能分布式键值存储系统。\n- **Quantum Simulator**：轻量级量子态矢量仿真器与 Bloch 球面演化工具。\n"
};
window.BlogSampleData = window.BlogPostsData; // Backwards compatibility
