/** Auto-generated by sync_posts.py - Do not edit manually */
window.BlogPostsData = {
  "generatedAt": "2026-10-10 09:35:10",
  "posts": [
    {
      "id": "post-col-抽象代数-02-群论测试",
      "slug": "02-群论测试",
      "title": "02 群论基础概念测试文档",
      "category": "general",
      "section": "columns",
      "column": "抽象代数",
      "columnName": "抽象代数",
      "project": "",
      "projectName": "",
      "order": 2,
      "relPath": "02-群论测试.md",
      "date": "2026-10-09",
      "readTime": "2 min read",
      "words": 566,
      "views": 1,
      "likes": 0,
      "pinned": false,
      "type": "post",
      "isTest": true,
      "slide": "",
      "attachments": [],
      "tocLevels": null,
      "excerpt": "这是一篇包含 test 标签的专栏测试文档，用于验证专栏路由与测试文档过滤开关。",
      "tags": [
        "test",
        "algebra"
      ],
      "content": "# 02 群论基础概念测试文档\n\n本文是一篇专栏测试文档，用于验证专栏路由、FrontMatter 专栏识别以及测试文档排除开关。\n\n## 群的公理定义\n\n一个群 $$(G, \\cdot)$$ 是由集合 $$G$$ 和二元运算 $$\\cdot$$ 组成的代数系统，满足以下四条公理：\n\n1. **封闭性 (Closure)**：对任意 $$a, b \\in G$$，有 $$a \\cdot b \\in G$$。\n2. **结合律 (Associativity)**：对任意 $$a, b, c \\in G$$，有 $$(a \\cdot b) \\cdot c = a \\cdot (b \\cdot c)$$。\n3. **单位元 (Identity)**：存在 $$e \\in G$$，使得对任意 $$a \\in G$$，有 $$a \\cdot e = e \\cdot a = a$$。\n4. **逆元 (Inverse)**：对任意 $$a \\in G$$，存在 $$a^{-1} \\in G$$，使得 $$a \\cdot a^{-1} = e$$。\n\n::: tip 测试提示\n当 blog.config.js 中的 `exclude.showTest` 设置为 false 时，此篇带有 test 标签的文章将被自动隐藏。\n:::"
    },
    {
      "id": "post-hello-world",
      "slug": "hello-world",
      "title": "Hello World: Welcome to Your Aurora Blog",
      "category": "general",
      "section": "posts",
      "column": "",
      "columnName": "",
      "project": "",
      "projectName": "",
      "order": 999,
      "relPath": "hello-world.md",
      "date": "2026-10-09",
      "readTime": "4 min read",
      "words": 1278,
      "views": 1,
      "likes": 0,
      "pinned": true,
      "type": "post",
      "isTest": false,
      "slide": "",
      "attachments": [],
      "tocLevels": null,
      "excerpt": "Welcome to your new personal blog, designed with Linear and Vercel-inspired dark minimalism.   Getting Started  Writing a new article is as...",
      "tags": [
        "Engineering",
        "Getting Started",
        "Markdown"
      ],
      "content": "Welcome to your new personal blog, designed with Linear and Vercel-inspired dark minimalism.\n\n## Getting Started\n\nWriting a new article is as simple as placing a Markdown file in the `posts/` directory.\n\n### Folder Structure\n\n- **Regular Articles**: Save any `.md` file directly in `posts/` or under category folders like `posts/tech/my-article.md`.\n- **Series / Columns**: Create a subdirectory inside `posts/columns/`, for example `posts/columns/system-design/01-introduction.md`.\n\n## Features Showcase\n\nHere is a quick demonstration of built-in capabilities:\n\n### 1. Mathematical Formulas (KaTeX)\n\nInline formulas like $$E = mc^2$$ or $$\\left| \\psi \\right\\rangle = \\alpha \\left| 0 \\right\\rangle + \\beta \\left| 1 \\right\\rangle$$, and block equations:\n\n$$\n\\mathcal{L} = \\mathbb{E}_{x \\sim p_{\\text{data}}} \\left[ \\log D(x) \\right] + \\mathbb{E}_{z \\sim p_z} \\left[ \\log (1 - D(G(z))) \\right]\n$$\n\n### 2. Code Highlighting & One-Click Copy\n\n```python\ndef fibonacci(n: int) -> int:\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n\nprint([fibonacci(i) for i in range(10)])\n```\n\n### 3. Callout Boxes\n\n::: tip Quick Publishing\nRun `./deploy.sh` to compile Markdown articles and push changes to GitHub Pages automatically.\n:::\n\nEnjoy crafting your writings!"
    },
    {
      "id": "post-page看看啥回事",
      "slug": "page看看啥回事",
      "title": "个人发展路线图与白皮书",
      "category": "general",
      "section": "posts",
      "column": "",
      "columnName": "",
      "project": "",
      "projectName": "",
      "order": 999,
      "relPath": "page看看啥回事.md",
      "date": "2026-10-10",
      "readTime": "1 min read",
      "words": 438,
      "views": 1,
      "likes": 0,
      "pinned": false,
      "type": "page",
      "isTest": false,
      "slide": "",
      "attachments": [],
      "tocLevels": [
        2,
        3
      ],
      "excerpt": "关于个人知识库使用约定、开源许可声明与项目发展演进路线图。",
      "tags": [
        "general"
      ],
      "content": "本白皮书是采用 **独立单页模式 (Page Mode)** 排版的示例，不仅支持完整的经历时间线导轨（Timeline Track）、关注领域与项目卡片，还支持完整的 KaTeX 数学公式与 Prism 代码高亮。\n\n## 知识共享许可协议\n\n本站所有原创研究笔记与系统设计图纸，除特别注明外，均遵循 **CC BY-NC-SA 4.0** 国际知识共享许可协议。\n\n## 引用规范示例\n\n在学术论文、学位报告或技术文档中引用本站内容时，建议采用如下 BibTeX 格式：\n\n```bibtex\n@online{aurora_notes_2026,\n  author = {CCC},\n  title = {Aurora Notes: Computing Fundamentals and Systems Architecture},\n  year = {2026},\n  url = {https://github.com/flyingpig669/blog}\n}\n```"
    },
    {
      "id": "post-quantum-simulator",
      "slug": "quantum-simulator",
      "title": "量子态矢量模拟引擎设计",
      "category": "physics",
      "section": "posts",
      "column": "",
      "columnName": "",
      "project": "",
      "projectName": "",
      "order": 999,
      "relPath": "quantum-simulator.md",
      "date": "2026-10-09",
      "readTime": "1 min read",
      "words": 397,
      "views": 1,
      "likes": 0,
      "pinned": false,
      "type": "post",
      "isTest": true,
      "slide": "attachments/slides/quantum-computing-slides.pdf",
      "attachments": [],
      "tocLevels": null,
      "excerpt": "基于高维复希尔伯特空间演化的轻量级量子计算仿真核心架构，附带演讲幻灯片展示。",
      "tags": [
        "quantum",
        "systems",
        "test"
      ],
      "content": "# 量子态矢量模拟引擎设计\n\n本项目是一个基于 Python/NumPy 构建的高性能量子态矢量演化仿真器，支持参数化变分量子电路（VQC）与 Bloch 球面状态投影。\n\n## 幻灯片演示 (Slide Presentation)\n\n以下是该项目的学术汇报 PPT 演示幻灯片：\n\n::: slide attachments/slides/quantum-computing-slides.pdf\n量子计算与态矢量演化汇报 PPT 演示\n:::\n\n## 态矢量数学表示\n\n任意单量子比特纯态可以表示为二维复希尔伯特空间中的单位向量：\n\n$$\n\\left| \\psi \\right\\rangle = \\alpha \\left| 0 \\right\\rangle + \\beta \\left| 1 \\right\\rangle, \\quad |\\alpha|^2 + |\\beta|^2 = 1\n$$"
    },
    {
      "id": "post-col-抽象代数-01-简介",
      "slug": "01-简介",
      "title": "01 简介：代数结构与映射",
      "category": "群论",
      "section": "columns",
      "column": "抽象代数",
      "columnName": "抽象代数与群论导引",
      "project": "",
      "projectName": "",
      "order": 1,
      "relPath": "群论/01-简介.md",
      "date": "2026-10-09",
      "readTime": "1 min read",
      "words": 276,
      "views": 1,
      "likes": 0,
      "pinned": false,
      "type": "post",
      "isTest": false,
      "slide": "",
      "attachments": [],
      "tocLevels": null,
      "excerpt": "抽象代数研究代数结构及其公理化体系，从对称性到群环域。",
      "tags": [
        "algebra",
        "math"
      ],
      "content": "# 01 简介：代数结构与映射\n\n抽象代数（Abstract Algebra）是近代数学的核心基石之一，致力于从具体的算术和多项式运算中提炼出抽象的代数结构。\n\n## 核心研究对象\n\n1. **半群与单子 (Semigroups & Monoids)**：配备结合律的二元代数系统。\n2. **群 (Groups)**：捕捉自然界物理对称性与几何变换的核心语言。\n3. **环与域 (Rings & Fields)**：兼具加法与乘法运算的严密代数系统。\n\n$$\n(a \\cdot b) \\cdot c = a \\cdot (b \\cdot c)\n$$"
    }
  ],
  "columns": [
    {
      "id": "抽象代数",
      "name": "抽象代数",
      "desc": "Technical series collection for 抽象代数.",
      "icon": "layers",
      "posts": [
        {
          "id": "post-col-抽象代数-01-简介",
          "slug": "01-简介",
          "title": "01 简介：代数结构与映射",
          "category": "群论",
          "section": "columns",
          "column": "抽象代数",
          "columnName": "抽象代数与群论导引",
          "project": "",
          "projectName": "",
          "order": 1,
          "relPath": "群论/01-简介.md",
          "date": "2026-10-09",
          "readTime": "1 min read",
          "words": 276,
          "views": 1,
          "likes": 0,
          "pinned": false,
          "type": "post",
          "isTest": false,
          "slide": "",
          "attachments": [],
          "tocLevels": null,
          "excerpt": "抽象代数研究代数结构及其公理化体系，从对称性到群环域。",
          "tags": [
            "algebra",
            "math"
          ],
          "content": "# 01 简介：代数结构与映射\n\n抽象代数（Abstract Algebra）是近代数学的核心基石之一，致力于从具体的算术和多项式运算中提炼出抽象的代数结构。\n\n## 核心研究对象\n\n1. **半群与单子 (Semigroups & Monoids)**：配备结合律的二元代数系统。\n2. **群 (Groups)**：捕捉自然界物理对称性与几何变换的核心语言。\n3. **环与域 (Rings & Fields)**：兼具加法与乘法运算的严密代数系统。\n\n$$\n(a \\cdot b) \\cdot c = a \\cdot (b \\cdot c)\n$$"
        },
        {
          "id": "post-col-抽象代数-02-群论测试",
          "slug": "02-群论测试",
          "title": "02 群论基础概念测试文档",
          "category": "general",
          "section": "columns",
          "column": "抽象代数",
          "columnName": "抽象代数",
          "project": "",
          "projectName": "",
          "order": 2,
          "relPath": "02-群论测试.md",
          "date": "2026-10-09",
          "readTime": "2 min read",
          "words": 566,
          "views": 1,
          "likes": 0,
          "pinned": false,
          "type": "post",
          "isTest": true,
          "slide": "",
          "attachments": [],
          "tocLevels": null,
          "excerpt": "这是一篇包含 test 标签的专栏测试文档，用于验证专栏路由与测试文档过滤开关。",
          "tags": [
            "test",
            "algebra"
          ],
          "content": "# 02 群论基础概念测试文档\n\n本文是一篇专栏测试文档，用于验证专栏路由、FrontMatter 专栏识别以及测试文档排除开关。\n\n## 群的公理定义\n\n一个群 $$(G, \\cdot)$$ 是由集合 $$G$$ 和二元运算 $$\\cdot$$ 组成的代数系统，满足以下四条公理：\n\n1. **封闭性 (Closure)**：对任意 $$a, b \\in G$$，有 $$a \\cdot b \\in G$$。\n2. **结合律 (Associativity)**：对任意 $$a, b, c \\in G$$，有 $$(a \\cdot b) \\cdot c = a \\cdot (b \\cdot c)$$。\n3. **单位元 (Identity)**：存在 $$e \\in G$$，使得对任意 $$a \\in G$$，有 $$a \\cdot e = e \\cdot a = a$$。\n4. **逆元 (Inverse)**：对任意 $$a \\in G$$，存在 $$a^{-1} \\in G$$，使得 $$a \\cdot a^{-1} = e$$。\n\n::: tip 测试提示\n当 blog.config.js 中的 `exclude.showTest` 设置为 false 时，此篇带有 test 标签的文章将被自动隐藏。\n:::"
        }
      ],
      "postsCount": 2,
      "totalWords": 842
    }
  ],
  "projects": [],
  "about": {
    "title": "About",
    "status": "Physics, Math & Computer Science",
    "quote": "Turning complexity into clean order through rigorous logic, mathematics, and craft.",
    "bio": "热爱理论物理与计算机科学的交叉前沿。致力于从高维希尔伯特空间、哈密顿量演化与微观统计力学的物理视角，理解并构建现代大规模计算架构与复杂分布式系统。坚持极简主义与深度心流开发，崇尚用严谨的数学推导与干净的代码建立秩序。",
    "timeline": [
      {
        "period": "2024 – PRESENT",
        "title": "架构设计与前沿计算探索",
        "desc": "深耕高吞吐分布式共识算法（Raft / Paxos）与容灾架构；探索量子线路变分模拟、张量网络计算与自注意力机制的数学同构。"
      },
      {
        "period": "2022 – 2024",
        "title": "核心系统研发与基础设施优化",
        "desc": "主导云原生后端基础设施重构，优化微服务拓扑与多级缓存一致性；搭建端到端高可用监控体系。"
      },
      {
        "period": "2020 – 2022",
        "title": "现代 Web 架构与工程化探索",
        "desc": "深入探索现代前端响应式渲染引擎演进（Virtual DOM Diff、Signals 与 Server Components）；活跃于开源社区。"
      }
    ],
    "focusAreas": [
      {
        "title": "分布式系统与高可用架构",
        "desc": "分布式共识协议、一致性存储模型与高并发中间件开发。"
      },
      {
        "title": "数学与理论物理同构",
        "desc": "复线性代数、高维希尔伯特空间、信息熵与统计热力学。"
      },
      {
        "title": "现代化工程美学",
        "desc": "精细化 Design Tokens、极简暗色交互与极致留白秩序。"
      }
    ],
    "projects": [
      {
        "name": "Aurora Notes",
        "tag": "Open Source",
        "desc": "冷静、克制、严谨的深色科技风个人博客系统。",
        "url": "https://github.com/flyingpig669/blog"
      },
      {
        "name": "Distributed Engine",
        "tag": "Go / Systems",
        "desc": "基于 Raft 协议构建的高性能分布式键值存储系统。",
        "url": "https://github.com/flyingpig669"
      },
      {
        "name": "Quantum Simulator",
        "tag": "Python / Physics",
        "desc": "轻量级态矢量仿真器与 Bloch 球面演化工具。",
        "url": "https://github.com/flyingpig669"
      }
    ],
    "social": [
      {
        "name": "GitHub",
        "url": "https://github.com/flyingpig669"
      },
      {
        "name": "Twitter",
        "url": "https://twitter.com"
      },
      {
        "name": "Email",
        "url": "mailto:flyingpig06@outlook.com"
      }
    ],
    "contacts": [],
    "links": [],
    "notes": "",
    "content": "",
    "raw": "---\n# 状态标签与个人座右铭\nstatus: \"Physics, Math & Computer Science\"\nquote: \"Turning complexity into clean order through rigorous logic, mathematics, and craft.\"\nbio: \"热爱理论物理与计算机科学的交叉前沿。致力于从高维希尔伯特空间、哈密顿量演化与微观统计力学的物理视角，理解并构建现代大规模计算架构与复杂分布式系统。坚持极简主义与深度心流开发，崇尚用严谨的数学推导与干净的代码建立秩序。\"\n\n# 经历与时间线 (Timeline & Milestones) - 记录在哪个时间段做了一些事情\ntimeline:\n  - period: \"2024 – PRESENT\"\n    title: \"架构设计与前沿计算探索\"\n    desc: \"深耕高吞吐分布式共识算法（Raft / Paxos）与容灾架构；探索量子线路变分模拟、张量网络计算与自注意力机制的数学同构。\"\n  - period: \"2022 – 2024\"\n    title: \"核心系统研发与基础设施优化\"\n    desc: \"主导云原生后端基础设施重构，优化微服务拓扑与多级缓存一致性；搭建端到端高可用监控体系。\"\n  - period: \"2020 – 2022\"\n    title: \"现代 Web 架构与工程化探索\"\n    desc: \"深入探索现代前端响应式渲染引擎演进（Virtual DOM Diff、Signals 与 Server Components）；活跃于开源社区。\"\n\n# 核心关注领域 (Focus Areas)\nfocusAreas:\n  - title: \"分布式系统与高可用架构\"\n    desc: \"分布式共识协议、一致性存储模型与高并发中间件开发。\"\n  - title: \"数学与理论物理同构\"\n    desc: \"复线性代数、高维希尔伯特空间、信息熵与统计热力学。\"\n  - title: \"现代化工程美学\"\n    desc: \"精细化 Design Tokens、极简暗色交互与极致留白秩序。\"\n\n# 社交渠道与个人主页 (Contacts) - 纯文字极简展示，支持在此任意扩展任意平台与主页\nsocial:\n  - name: \"GitHub\"\n    url: \"https://github.com/flyingpig669\"\n  - name: \"Twitter\"\n    url: \"https://twitter.com\"\n  - name: \"Email\"\n    url: \"mailto:flyingpig06@outlook.com\"\n\n# 精选项目 (Selected Projects)\nprojects:\n  - name: \"Aurora Notes\"\n    tag: \"Open Source\"\n    desc: \"冷静、克制、严谨的深色科技风个人博客系统。\"\n    url: \"https://github.com/flyingpig669/blog\"\n  - name: \"Distributed Engine\"\n    tag: \"Go / Systems\"\n    desc: \"基于 Raft 协议构建的高性能分布式键值存储系统。\"\n    url: \"https://github.com/flyingpig669\"\n  - name: \"Quantum Simulator\"\n    tag: \"Python / Physics\"\n    desc: \"轻量级态矢量仿真器与 Bloch 球面演化工具。\"\n    url: \"https://github.com/flyingpig669\"\n---\n",
    "tocLevels": null
  },
  "pages": {
    "about": {
      "title": "About",
      "status": "Physics, Math & Computer Science",
      "quote": "Turning complexity into clean order through rigorous logic, mathematics, and craft.",
      "bio": "热爱理论物理与计算机科学的交叉前沿。致力于从高维希尔伯特空间、哈密顿量演化与微观统计力学的物理视角，理解并构建现代大规模计算架构与复杂分布式系统。坚持极简主义与深度心流开发，崇尚用严谨的数学推导与干净的代码建立秩序。",
      "timeline": [
        {
          "period": "2024 – PRESENT",
          "title": "架构设计与前沿计算探索",
          "desc": "深耕高吞吐分布式共识算法（Raft / Paxos）与容灾架构；探索量子线路变分模拟、张量网络计算与自注意力机制的数学同构。"
        },
        {
          "period": "2022 – 2024",
          "title": "核心系统研发与基础设施优化",
          "desc": "主导云原生后端基础设施重构，优化微服务拓扑与多级缓存一致性；搭建端到端高可用监控体系。"
        },
        {
          "period": "2020 – 2022",
          "title": "现代 Web 架构与工程化探索",
          "desc": "深入探索现代前端响应式渲染引擎演进（Virtual DOM Diff、Signals 与 Server Components）；活跃于开源社区。"
        }
      ],
      "focusAreas": [
        {
          "title": "分布式系统与高可用架构",
          "desc": "分布式共识协议、一致性存储模型与高并发中间件开发。"
        },
        {
          "title": "数学与理论物理同构",
          "desc": "复线性代数、高维希尔伯特空间、信息熵与统计热力学。"
        },
        {
          "title": "现代化工程美学",
          "desc": "精细化 Design Tokens、极简暗色交互与极致留白秩序。"
        }
      ],
      "projects": [
        {
          "name": "Aurora Notes",
          "tag": "Open Source",
          "desc": "冷静、克制、严谨的深色科技风个人博客系统。",
          "url": "https://github.com/flyingpig669/blog"
        },
        {
          "name": "Distributed Engine",
          "tag": "Go / Systems",
          "desc": "基于 Raft 协议构建的高性能分布式键值存储系统。",
          "url": "https://github.com/flyingpig669"
        },
        {
          "name": "Quantum Simulator",
          "tag": "Python / Physics",
          "desc": "轻量级态矢量仿真器与 Bloch 球面演化工具。",
          "url": "https://github.com/flyingpig669"
        }
      ],
      "social": [
        {
          "name": "GitHub",
          "url": "https://github.com/flyingpig669"
        },
        {
          "name": "Twitter",
          "url": "https://twitter.com"
        },
        {
          "name": "Email",
          "url": "mailto:flyingpig06@outlook.com"
        }
      ],
      "contacts": [],
      "links": [],
      "notes": "",
      "content": "",
      "raw": "---\n# 状态标签与个人座右铭\nstatus: \"Physics, Math & Computer Science\"\nquote: \"Turning complexity into clean order through rigorous logic, mathematics, and craft.\"\nbio: \"热爱理论物理与计算机科学的交叉前沿。致力于从高维希尔伯特空间、哈密顿量演化与微观统计力学的物理视角，理解并构建现代大规模计算架构与复杂分布式系统。坚持极简主义与深度心流开发，崇尚用严谨的数学推导与干净的代码建立秩序。\"\n\n# 经历与时间线 (Timeline & Milestones) - 记录在哪个时间段做了一些事情\ntimeline:\n  - period: \"2024 – PRESENT\"\n    title: \"架构设计与前沿计算探索\"\n    desc: \"深耕高吞吐分布式共识算法（Raft / Paxos）与容灾架构；探索量子线路变分模拟、张量网络计算与自注意力机制的数学同构。\"\n  - period: \"2022 – 2024\"\n    title: \"核心系统研发与基础设施优化\"\n    desc: \"主导云原生后端基础设施重构，优化微服务拓扑与多级缓存一致性；搭建端到端高可用监控体系。\"\n  - period: \"2020 – 2022\"\n    title: \"现代 Web 架构与工程化探索\"\n    desc: \"深入探索现代前端响应式渲染引擎演进（Virtual DOM Diff、Signals 与 Server Components）；活跃于开源社区。\"\n\n# 核心关注领域 (Focus Areas)\nfocusAreas:\n  - title: \"分布式系统与高可用架构\"\n    desc: \"分布式共识协议、一致性存储模型与高并发中间件开发。\"\n  - title: \"数学与理论物理同构\"\n    desc: \"复线性代数、高维希尔伯特空间、信息熵与统计热力学。\"\n  - title: \"现代化工程美学\"\n    desc: \"精细化 Design Tokens、极简暗色交互与极致留白秩序。\"\n\n# 社交渠道与个人主页 (Contacts) - 纯文字极简展示，支持在此任意扩展任意平台与主页\nsocial:\n  - name: \"GitHub\"\n    url: \"https://github.com/flyingpig669\"\n  - name: \"Twitter\"\n    url: \"https://twitter.com\"\n  - name: \"Email\"\n    url: \"mailto:flyingpig06@outlook.com\"\n\n# 精选项目 (Selected Projects)\nprojects:\n  - name: \"Aurora Notes\"\n    tag: \"Open Source\"\n    desc: \"冷静、克制、严谨的深色科技风个人博客系统。\"\n    url: \"https://github.com/flyingpig669/blog\"\n  - name: \"Distributed Engine\"\n    tag: \"Go / Systems\"\n    desc: \"基于 Raft 协议构建的高性能分布式键值存储系统。\"\n    url: \"https://github.com/flyingpig669\"\n  - name: \"Quantum Simulator\"\n    tag: \"Python / Physics\"\n    desc: \"轻量级态矢量仿真器与 Bloch 球面演化工具。\"\n    url: \"https://github.com/flyingpig669\"\n---\n",
      "tocLevels": null
    },
    "about.md": {
      "title": "About",
      "status": "Physics, Math & Computer Science",
      "quote": "Turning complexity into clean order through rigorous logic, mathematics, and craft.",
      "bio": "热爱理论物理与计算机科学的交叉前沿。致力于从高维希尔伯特空间、哈密顿量演化与微观统计力学的物理视角，理解并构建现代大规模计算架构与复杂分布式系统。坚持极简主义与深度心流开发，崇尚用严谨的数学推导与干净的代码建立秩序。",
      "timeline": [
        {
          "period": "2024 – PRESENT",
          "title": "架构设计与前沿计算探索",
          "desc": "深耕高吞吐分布式共识算法（Raft / Paxos）与容灾架构；探索量子线路变分模拟、张量网络计算与自注意力机制的数学同构。"
        },
        {
          "period": "2022 – 2024",
          "title": "核心系统研发与基础设施优化",
          "desc": "主导云原生后端基础设施重构，优化微服务拓扑与多级缓存一致性；搭建端到端高可用监控体系。"
        },
        {
          "period": "2020 – 2022",
          "title": "现代 Web 架构与工程化探索",
          "desc": "深入探索现代前端响应式渲染引擎演进（Virtual DOM Diff、Signals 与 Server Components）；活跃于开源社区。"
        }
      ],
      "focusAreas": [
        {
          "title": "分布式系统与高可用架构",
          "desc": "分布式共识协议、一致性存储模型与高并发中间件开发。"
        },
        {
          "title": "数学与理论物理同构",
          "desc": "复线性代数、高维希尔伯特空间、信息熵与统计热力学。"
        },
        {
          "title": "现代化工程美学",
          "desc": "精细化 Design Tokens、极简暗色交互与极致留白秩序。"
        }
      ],
      "projects": [
        {
          "name": "Aurora Notes",
          "tag": "Open Source",
          "desc": "冷静、克制、严谨的深色科技风个人博客系统。",
          "url": "https://github.com/flyingpig669/blog"
        },
        {
          "name": "Distributed Engine",
          "tag": "Go / Systems",
          "desc": "基于 Raft 协议构建的高性能分布式键值存储系统。",
          "url": "https://github.com/flyingpig669"
        },
        {
          "name": "Quantum Simulator",
          "tag": "Python / Physics",
          "desc": "轻量级态矢量仿真器与 Bloch 球面演化工具。",
          "url": "https://github.com/flyingpig669"
        }
      ],
      "social": [
        {
          "name": "GitHub",
          "url": "https://github.com/flyingpig669"
        },
        {
          "name": "Twitter",
          "url": "https://twitter.com"
        },
        {
          "name": "Email",
          "url": "mailto:flyingpig06@outlook.com"
        }
      ],
      "contacts": [],
      "links": [],
      "notes": "",
      "content": "",
      "raw": "---\n# 状态标签与个人座右铭\nstatus: \"Physics, Math & Computer Science\"\nquote: \"Turning complexity into clean order through rigorous logic, mathematics, and craft.\"\nbio: \"热爱理论物理与计算机科学的交叉前沿。致力于从高维希尔伯特空间、哈密顿量演化与微观统计力学的物理视角，理解并构建现代大规模计算架构与复杂分布式系统。坚持极简主义与深度心流开发，崇尚用严谨的数学推导与干净的代码建立秩序。\"\n\n# 经历与时间线 (Timeline & Milestones) - 记录在哪个时间段做了一些事情\ntimeline:\n  - period: \"2024 – PRESENT\"\n    title: \"架构设计与前沿计算探索\"\n    desc: \"深耕高吞吐分布式共识算法（Raft / Paxos）与容灾架构；探索量子线路变分模拟、张量网络计算与自注意力机制的数学同构。\"\n  - period: \"2022 – 2024\"\n    title: \"核心系统研发与基础设施优化\"\n    desc: \"主导云原生后端基础设施重构，优化微服务拓扑与多级缓存一致性；搭建端到端高可用监控体系。\"\n  - period: \"2020 – 2022\"\n    title: \"现代 Web 架构与工程化探索\"\n    desc: \"深入探索现代前端响应式渲染引擎演进（Virtual DOM Diff、Signals 与 Server Components）；活跃于开源社区。\"\n\n# 核心关注领域 (Focus Areas)\nfocusAreas:\n  - title: \"分布式系统与高可用架构\"\n    desc: \"分布式共识协议、一致性存储模型与高并发中间件开发。\"\n  - title: \"数学与理论物理同构\"\n    desc: \"复线性代数、高维希尔伯特空间、信息熵与统计热力学。\"\n  - title: \"现代化工程美学\"\n    desc: \"精细化 Design Tokens、极简暗色交互与极致留白秩序。\"\n\n# 社交渠道与个人主页 (Contacts) - 纯文字极简展示，支持在此任意扩展任意平台与主页\nsocial:\n  - name: \"GitHub\"\n    url: \"https://github.com/flyingpig669\"\n  - name: \"Twitter\"\n    url: \"https://twitter.com\"\n  - name: \"Email\"\n    url: \"mailto:flyingpig06@outlook.com\"\n\n# 精选项目 (Selected Projects)\nprojects:\n  - name: \"Aurora Notes\"\n    tag: \"Open Source\"\n    desc: \"冷静、克制、严谨的深色科技风个人博客系统。\"\n    url: \"https://github.com/flyingpig669/blog\"\n  - name: \"Distributed Engine\"\n    tag: \"Go / Systems\"\n    desc: \"基于 Raft 协议构建的高性能分布式键值存储系统。\"\n    url: \"https://github.com/flyingpig669\"\n  - name: \"Quantum Simulator\"\n    tag: \"Python / Physics\"\n    desc: \"轻量级态矢量仿真器与 Bloch 球面演化工具。\"\n    url: \"https://github.com/flyingpig669\"\n---\n",
      "tocLevels": null
    },
    "page看看啥回事": {
      "title": "个人发展路线图与白皮书",
      "status": "",
      "quote": "",
      "bio": "",
      "timeline": [
        {
          "period": "2026 – FUTURE",
          "title": "前沿量子计算与分布式引擎开源",
          "desc": "发布高性能量子态矢量仿真器核心，推进变分量子算法工程落地。"
        },
        {
          "period": "2024 – 2026",
          "title": "Aurora Notes 极简科技知识库构建",
          "desc": "设计并研发遵循 Linear / Raycast 规范的深色极简博客系统，深度优化学术数学公式与演示文稿放映。"
        },
        {
          "period": "2022 – 2024",
          "title": "系统底层架构与并发模型探索",
          "desc": "深耕分布式共识协议、无锁队列与内存局部性高吞吐优化。"
        }
      ],
      "focusAreas": [
        {
          "title": "分布式系统与高可用架构",
          "desc": "深入一致性共识算法与高可用基础设施拓扑。"
        },
        {
          "title": "量子计算与理论物理",
          "desc": "高维复希尔伯特空间演化、量子门分解与变分量子算法。"
        }
      ],
      "projects": [],
      "social": [],
      "contacts": [],
      "links": [],
      "notes": "本白皮书是采用 **独立单页模式 (Page Mode)** 排版的示例，不仅支持完整的经历时间线导轨（Timeline Track）、关注领域与项目卡片，还支持完整的 KaTeX 数学公式与 Prism 代码高亮。\n\n## 知识共享许可协议\n\n本站所有原创研究笔记与系统设计图纸，除特别注明外，均遵循 **CC BY-NC-SA 4.0** 国际知识共享许可协议。\n\n## 引用规范示例\n\n在学术论文、学位报告或技术文档中引用本站内容时，建议采用如下 BibTeX 格式：\n\n```bibtex\n@online{aurora_notes_2026,\n  author = {CCC},\n  title = {Aurora Notes: Computing Fundamentals and Systems Architecture},\n  year = {2026},\n  url = {https://github.com/flyingpig669/blog}\n}\n```",
      "content": "",
      "raw": "---\ntitle: \"个人发展路线图与白皮书\"\ntype: \"page\"              # 开启独立单页模式（不展示发布时间流水账与底部翻页，纯净居中）\nexcerpt: \"关于个人知识库使用约定、开源许可声明与项目发展演进路线图。\"\ntocLevels: [2, 3]\n\n# 经历与时间线 (Timeline & Milestones) - 记录在哪个时间段做了一些事情\ntimeline:\n  - period: \"2026 – FUTURE\"\n    title: \"前沿量子计算与分布式引擎开源\"\n    desc: \"发布高性能量子态矢量仿真器核心，推进变分量子算法工程落地。\"\n  - period: \"2024 – 2026\"\n    title: \"Aurora Notes 极简科技知识库构建\"\n    desc: \"设计并研发遵循 Linear / Raycast 规范的深色极简博客系统，深度优化学术数学公式与演示文稿放映。\"\n  - period: \"2022 – 2024\"\n    title: \"系统底层架构与并发模型探索\"\n    desc: \"深耕分布式共识协议、无锁队列与内存局部性高吞吐优化。\"\n\n# 核心关注领域 (Focus Areas)\nfocusAreas:\n  - title: \"分布式系统与高可用架构\"\n    desc: \"深入一致性共识算法与高可用基础设施拓扑。\"\n  - title: \"量子计算与理论物理\"\n    desc: \"高维复希尔伯特空间演化、量子门分解与变分量子算法。\"\n---\n\n本白皮书是采用 **独立单页模式 (Page Mode)** 排版的示例，不仅支持完整的经历时间线导轨（Timeline Track）、关注领域与项目卡片，还支持完整的 KaTeX 数学公式与 Prism 代码高亮。\n\n## 知识共享许可协议\n\n本站所有原创研究笔记与系统设计图纸，除特别注明外，均遵循 **CC BY-NC-SA 4.0** 国际知识共享许可协议。\n\n## 引用规范示例\n\n在学术论文、学位报告或技术文档中引用本站内容时，建议采用如下 BibTeX 格式：\n\n```bibtex\n@online{aurora_notes_2026,\n  author = {CCC},\n  title = {Aurora Notes: Computing Fundamentals and Systems Architecture},\n  year = {2026},\n  url = {https://github.com/flyingpig669/blog}\n}\n```\n",
      "tocLevels": "[2, 3]",
      "type": "page",
      "excerpt": "关于个人知识库使用约定、开源许可声明与项目发展演进路线图。"
    },
    "page看看啥回事.md": {
      "title": "个人发展路线图与白皮书",
      "status": "",
      "quote": "",
      "bio": "",
      "timeline": [
        {
          "period": "2026 – FUTURE",
          "title": "前沿量子计算与分布式引擎开源",
          "desc": "发布高性能量子态矢量仿真器核心，推进变分量子算法工程落地。"
        },
        {
          "period": "2024 – 2026",
          "title": "Aurora Notes 极简科技知识库构建",
          "desc": "设计并研发遵循 Linear / Raycast 规范的深色极简博客系统，深度优化学术数学公式与演示文稿放映。"
        },
        {
          "period": "2022 – 2024",
          "title": "系统底层架构与并发模型探索",
          "desc": "深耕分布式共识协议、无锁队列与内存局部性高吞吐优化。"
        }
      ],
      "focusAreas": [
        {
          "title": "分布式系统与高可用架构",
          "desc": "深入一致性共识算法与高可用基础设施拓扑。"
        },
        {
          "title": "量子计算与理论物理",
          "desc": "高维复希尔伯特空间演化、量子门分解与变分量子算法。"
        }
      ],
      "projects": [],
      "social": [],
      "contacts": [],
      "links": [],
      "notes": "本白皮书是采用 **独立单页模式 (Page Mode)** 排版的示例，不仅支持完整的经历时间线导轨（Timeline Track）、关注领域与项目卡片，还支持完整的 KaTeX 数学公式与 Prism 代码高亮。\n\n## 知识共享许可协议\n\n本站所有原创研究笔记与系统设计图纸，除特别注明外，均遵循 **CC BY-NC-SA 4.0** 国际知识共享许可协议。\n\n## 引用规范示例\n\n在学术论文、学位报告或技术文档中引用本站内容时，建议采用如下 BibTeX 格式：\n\n```bibtex\n@online{aurora_notes_2026,\n  author = {CCC},\n  title = {Aurora Notes: Computing Fundamentals and Systems Architecture},\n  year = {2026},\n  url = {https://github.com/flyingpig669/blog}\n}\n```",
      "content": "",
      "raw": "---\ntitle: \"个人发展路线图与白皮书\"\ntype: \"page\"              # 开启独立单页模式（不展示发布时间流水账与底部翻页，纯净居中）\nexcerpt: \"关于个人知识库使用约定、开源许可声明与项目发展演进路线图。\"\ntocLevels: [2, 3]\n\n# 经历与时间线 (Timeline & Milestones) - 记录在哪个时间段做了一些事情\ntimeline:\n  - period: \"2026 – FUTURE\"\n    title: \"前沿量子计算与分布式引擎开源\"\n    desc: \"发布高性能量子态矢量仿真器核心，推进变分量子算法工程落地。\"\n  - period: \"2024 – 2026\"\n    title: \"Aurora Notes 极简科技知识库构建\"\n    desc: \"设计并研发遵循 Linear / Raycast 规范的深色极简博客系统，深度优化学术数学公式与演示文稿放映。\"\n  - period: \"2022 – 2024\"\n    title: \"系统底层架构与并发模型探索\"\n    desc: \"深耕分布式共识协议、无锁队列与内存局部性高吞吐优化。\"\n\n# 核心关注领域 (Focus Areas)\nfocusAreas:\n  - title: \"分布式系统与高可用架构\"\n    desc: \"深入一致性共识算法与高可用基础设施拓扑。\"\n  - title: \"量子计算与理论物理\"\n    desc: \"高维复希尔伯特空间演化、量子门分解与变分量子算法。\"\n---\n\n本白皮书是采用 **独立单页模式 (Page Mode)** 排版的示例，不仅支持完整的经历时间线导轨（Timeline Track）、关注领域与项目卡片，还支持完整的 KaTeX 数学公式与 Prism 代码高亮。\n\n## 知识共享许可协议\n\n本站所有原创研究笔记与系统设计图纸，除特别注明外，均遵循 **CC BY-NC-SA 4.0** 国际知识共享许可协议。\n\n## 引用规范示例\n\n在学术论文、学位报告或技术文档中引用本站内容时，建议采用如下 BibTeX 格式：\n\n```bibtex\n@online{aurora_notes_2026,\n  author = {CCC},\n  title = {Aurora Notes: Computing Fundamentals and Systems Architecture},\n  year = {2026},\n  url = {https://github.com/flyingpig669/blog}\n}\n```\n",
      "tocLevels": "[2, 3]",
      "type": "page",
      "excerpt": "关于个人知识库使用约定、开源许可声明与项目发展演进路线图。"
    }
  },
  "customPages": {
    "page看看啥回事": "---\ntitle: \"个人发展路线图与白皮书\"\ntype: \"page\"              # 开启独立单页模式（不展示发布时间流水账与底部翻页，纯净居中）\nexcerpt: \"关于个人知识库使用约定、开源许可声明与项目发展演进路线图。\"\ntocLevels: [2, 3]\n\n# 经历与时间线 (Timeline & Milestones) - 记录在哪个时间段做了一些事情\ntimeline:\n  - period: \"2026 – FUTURE\"\n    title: \"前沿量子计算与分布式引擎开源\"\n    desc: \"发布高性能量子态矢量仿真器核心，推进变分量子算法工程落地。\"\n  - period: \"2024 – 2026\"\n    title: \"Aurora Notes 极简科技知识库构建\"\n    desc: \"设计并研发遵循 Linear / Raycast 规范的深色极简博客系统，深度优化学术数学公式与演示文稿放映。\"\n  - period: \"2022 – 2024\"\n    title: \"系统底层架构与并发模型探索\"\n    desc: \"深耕分布式共识协议、无锁队列与内存局部性高吞吐优化。\"\n\n# 核心关注领域 (Focus Areas)\nfocusAreas:\n  - title: \"分布式系统与高可用架构\"\n    desc: \"深入一致性共识算法与高可用基础设施拓扑。\"\n  - title: \"量子计算与理论物理\"\n    desc: \"高维复希尔伯特空间演化、量子门分解与变分量子算法。\"\n---\n\n本白皮书是采用 **独立单页模式 (Page Mode)** 排版的示例，不仅支持完整的经历时间线导轨（Timeline Track）、关注领域与项目卡片，还支持完整的 KaTeX 数学公式与 Prism 代码高亮。\n\n## 知识共享许可协议\n\n本站所有原创研究笔记与系统设计图纸，除特别注明外，均遵循 **CC BY-NC-SA 4.0** 国际知识共享许可协议。\n\n## 引用规范示例\n\n在学术论文、学位报告或技术文档中引用本站内容时，建议采用如下 BibTeX 格式：\n\n```bibtex\n@online{aurora_notes_2026,\n  author = {CCC},\n  title = {Aurora Notes: Computing Fundamentals and Systems Architecture},\n  year = {2026},\n  url = {https://github.com/flyingpig669/blog}\n}\n```\n"
  }
};
window.BlogSampleData = window.BlogPostsData; // Backwards compatibility
